/* text_output_utils.c
 * 
 * This source file provides implementation details for utility functions that enable text output.
 * It includes functions to print out a specially prepared string, generated by the
 * `text2tile_addreses.py` tool and to print out an 8-bit hexadecimal number.
 */
#include "text_output_utils.h"

void print_int8hex_win(uint8_t x,uint8_t y, uint8_t number){
	uchar_t buf[2];
	uchar_t first_part = (number & 0xF0) >> 4 ;
	uchar_t second_part = number & 0x0F;

	if ( first_part < 0xAu ){
		buf[0] = ANSII_NUMBERIC_OFFSET + first_part;
	} else {
		buf[0] = ANSII_ALPHABETIC_OFFSET + first_part;
	}

	if ( second_part < 0xAu ){
		buf[1] = ANSII_NUMBERIC_OFFSET + second_part;
	} else {
		buf[1] = ANSII_ALPHABETIC_OFFSET + second_part;
	}
	print_line_win(x, y, 2, buf); 
}
